language: node_js
node_js:
- 8.11.3
branchs:
  only:
  - master
script:
  - npm test
addons:
  ssh_known_hosts:
  - 114.55.249.161
before_install:
- openssl aes-256-cbc -K $encrypted_0690d495720c_key -iv $encrypted_0690d495720c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa   #Linux文件权限问题
- ssh www@114.55.249.161 -o StrictHostKeyChecking=no '~/update.sh sso'   #使用ssh连接服务器