# .travis.yml
language: node_js   #本项目基于node_js实现工程
node_js:
- '8'   #指定node版本
branchs:
  only:
  - master  #指定只有检测到master分支有变动时才执行任务
  before_install:   # 添加解密命令
- openssl aes-256-cbc -K $encrypted_****_key -iv $encrypted_****_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d